spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_db
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    sql:
      init:
        mode: never

  server:
    port: 8080

  logging:
    level:
      org.hibernate.SQL: warn
      org.springframework: info